name: Deploy to CapRover

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  deploy-to-caprover:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        env:
          SERVER: 'c.rbnu.nl'
          APP: 'the-movement'
          TOKEN: '${{ secrets.APP_TOKEN }}'
